### ISSUE TITLE
First login and tool_policy - block_accessibility is not working

### ISSUE THREAD

**Issue by amalkowski** [brickfield/moodle-block_accessibility#130]
Hi,

When I am trying to use a block on the policy page:
(First user login and forcing you to accept policies)
/admin/tool/policy/index.php

I get an error:
![block_accessibility-2021-08-05--09-08-50](https://user-images.githubusercontent.com/26254229/128307269-12c4a7ed-0c10-4f0e-8680-9b6440f7d3a0.png)

![block_accessibility-2021-08-05--09-18-20](https://user-images.githubusercontent.com/26254229/128308369-ff4bacfc-5b62-426a-b087-80096d3dcf50.png)

Moodle: 3.9.9 (Build: 20210729)
Block: 1.39.01 (Build - 2021071301)

**Comment by mchurchward** [comment]
Please check release 1.39.02. Login redirects have been fixed.
See #127

**Comment by amalkowski** [comment]
that does not fix the problem.

tool_policy force redirect on files changesize.php, changecolour.php, database.php and userstyles.php if user is before accepting the policy

it would be best to use define a constant NO_SITEPOLICY_CHECK form this file.

**Comment by mchurchward** [comment]
Sorry, I don't think I am understanding the problem. Can you post detailed steps to reproduce what you are seeing?

**Comment by amalkowski** [comment]
Steps:
1. Add block_accessibility to Site home
2. Configuring a Accessibility block -> Page contexts -> Set  Display throughout the entire site
3. Site administration > Users > Privacy and policies > Policy settings > Site policy handler set Policies (tool_policy)
4. Site administration > Users > Privacy and policies > Manage policies > New policy
5. Add new Site policy and check Policy status Active
6. Register new account and login
7. Moodle display Policies and agreements
8. Try use block_accessibility

**Comment by mchurchward** [comment]
Interestingly, it does work after the first use without being logged in. That is, it fails the first time, but works thereafter.

**Comment by mchurchward** [comment]
Can you try the code in branch [TW17223966](https://github.com/brickfield/moodle-block_accessibility/tree/TW17223966)? It has handlers in to deal with users that haven't agreed to the site policy and still need to use the block.
