### ISSUE TITLE
First login and tool_policy - block_accessibility wrong redirect

### ISSUE THREAD

**Issue by amalkowski** [brickfield/moodle-block_accessibility#131]
Hi,

When this block is on the privacy policie page
(First user login and forcing you to accept policies)
/admin/tool/policy/index.php

After accepting the privacy policies, the user is redirected to
/blocks/accessibility/changesize.php?op=inc&cur=100

![block_accessibility-2021-08-05--09-16-37](https://user-images.githubusercontent.com/26254229/128308223-cf2e6ec8-1fd9-4613-aeb8-abeb0d37ddd2.png)

Moodle: 3.9.9 (Build: 20210729)
Block: 1.39.01 (Build - 2021071301)

**Comment by mchurchward** [comment]
Please see issue #127 . This has been fixed

**Comment by amalkowski** [comment]
I tested it this morning.

This does not solve the problem on this page.

**Comment by mchurchward** [comment]
Is the same as issue #130 ?

**Comment by amalkowski** [comment]
No, I think the problem is more related to #127
